server:
  port: 8080

app-config:
  nome: ControleCandidatos
  versao: @project.version@
  url: http://localhost:${server.port}

spring:
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:controle-candidato-test-${random.uuid};MODE=Oracle;DB_CLOSE_DELAY=0
    username: sa
    password:
    driverClassName: org.h2.Driver
    hiraki:
      maximum-pool-size: 1